#!/usr/bin/env bash
# .claude/hooks/block-packed-files.sh
#
# PreToolUse gate (matcher: Edit|Write): the packed orb snapshot (src/ios.yml)
# and the repo-root packed copy (orb.yml) are generated by `cd src &&
# ./pack.sh` — never hand-edited. This denies any Edit/Write targeting them,
# in either the working tree or an already-packed copy.
set -euo pipefail

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(pwd)}"
INPUT_JSON="$(cat)"
FILE_PATH="$(jq -r '.tool_input.file_path // empty' <<< "${INPUT_JSON}")"

if [[ -z "${FILE_PATH}" ]]; then
    exit 0
fi

case "${FILE_PATH}" in
    "${PROJECT_DIR}"/*) REL_PATH="${FILE_PATH#"${PROJECT_DIR}"/}" ;;
    *) REL_PATH="${FILE_PATH}" ;;
esac

case "${REL_PATH}" in
    src/ios.yml | orb.yml)
        jq -n --arg path "${REL_PATH}" '{
            hookSpecificOutput: {
                hookEventName: "PreToolUse",
                permissionDecision: "deny",
                permissionDecisionReason: ("Refusing to edit the packed orb snapshot (" + $path + "). Edit the unpacked source under src/{commands,jobs,executors,examples}/ instead, then run `cd src && ./pack.sh`.")
            }
        }'
        exit 0
        ;;
    *)
        exit 0
        ;;
esac
