---
version: '2'
plugins:
    swiftlint:
        enabled: true
    bundler-audit:
        enabled: true
    rubocop:
        enabled: true
        channel: rubocop-1-23-0
    shellcheck:
        enabled: true
    markdownlint:
        enabled: true
exclude_patterns:
    - docs/
    - Documentation/
    - Configs/
    - fastlane/
    - Resources/
    - Templates/
    - Example/
    - Tests/
    - '**/*.css'
    - '**/spec/'
    - '**/test/'
    - '**/tests/'
    - '*file'
    - '*.lock'
