---
# MD012/no-multiple-blanks
MD012:
    maximum: 1

# MD013/line-length
MD013:
    line_length: 120
    code_block_line_length: 120
    code_blocks: true
    tables: false
    strict: false
    stern: false

# MD007/ul-indent
MD007:
    indent: 4
    start_indented: false
    start_indent: 4

# MD033/no-inline-html - Allow HTML in markdown
MD033: false
