---
version: 2.1
setup: true
orbs:
    orb-tools: circleci/orb-tools@12.1.0
    shellcheck: circleci/shellcheck@3.4.0

filters: &filters
    tags:
        only: /.*/

workflows:
    lint-pack:
        jobs:
            - orb-tools/lint:
                  filters: *filters
            - orb-tools/pack:
                  context: orb-publishing
                  filters: *filters
            - orb-tools/review:
                  exclude: RC006,RC007
                  filters: *filters
            - shellcheck/check:
                  filters: *filters
            - orb-tools/publish:
                  orb_name: kevnm67/ios-orb
                  vcs_type: << pipeline.project.type >>
                  requires: [orb-tools/lint, orb-tools/review, orb-tools/pack, shellcheck/check]
                  context: orb-publishing
                  filters: *filters
            - orb-tools/continue:
                  orb_name: ios-orb
                  pipeline_number: << pipeline.number >>
                  vcs_type: << pipeline.project.type >>
                  requires: [orb-tools/publish]
                  filters: *filters
